-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.brands
(
    brand_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    brand_name character varying(50),
    PRIMARY KEY (brand_id)
);

CREATE TABLE public.car_images
(
    image_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    car_id integer NOT NULL,
    date date,
    image_path character varying,
    PRIMARY KEY (image_id)
);

CREATE TABLE public.cars
(
    car_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    brand_id integer NOT NULL,
    color_id integer NOT NULL,
    model_year integer NOT NULL,
    daily_price double precision NOT NULL,
    car_name character varying(50) NOT NULL,
    PRIMARY KEY (car_id)
);

CREATE TABLE public.colours
(
    color_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    color_name character varying(50) NOT NULL,
    PRIMARY KEY (color_id)
);

CREATE TABLE public.credit_card
(
    card_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    customer_id integer NOT NULL,
    fullname character varying(100) NOT NULL,
    card_number integer NOT NULL,
    card_exp_month integer NOT NULL,
    card_exp_year integer NOT NULL,
    cvv integer NOT NULL,
    card_type character varying(100) NOT NULL,
    card_limit integer NOT NULL,
    PRIMARY KEY (card_id)
);

CREATE TABLE public.customers
(
    customer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    company_name character varying(50),
    user_id integer NOT NULL,
    PRIMARY KEY (customer_id)
);

CREATE TABLE public.operation_claims
(
    claim_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    claim_name character varying NOT NULL,
    PRIMARY KEY (claim_id)
);

CREATE TABLE public.payment
(
    payment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    customer_id integer NOT NULL,
    amount integer NOT NULL,
    PRIMARY KEY (payment_id)
);

CREATE TABLE public.rentals
(
    rental_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    car_id integer NOT NULL,
    customer_id integer NOT NULL,
    rent_date date NOT NULL,
    return_date date,
    PRIMARY KEY (rental_id)
);

CREATE TABLE public.user_operation_claims
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    userss_id integer NOT NULL,
    operation_claim_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.userss
(
    userss_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    email character varying(50) NOT NULL,
    password_salt bytea,
    password_hash bytea,
    status boolean,
    PRIMARY KEY (userss_id)
);

ALTER TABLE public.car_images
    ADD FOREIGN KEY (car_id)
    REFERENCES public.cars (car_id)
    NOT VALID;


ALTER TABLE public.cars
    ADD FOREIGN KEY (brand_id)
    REFERENCES public.brands (brand_id)
    NOT VALID;


ALTER TABLE public.cars
    ADD FOREIGN KEY (color_id)
    REFERENCES public.colours (color_id)
    NOT VALID;


ALTER TABLE public.customers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.userss (userss_id)
    NOT VALID;

END;